SHELL := /bin/sh
ZPC = /zz
DIGICONFIG = /home/${LOGNAME}/.config/digikamrc

.PHONY: help
help: ## Show this help
	@egrep -h '\s##\s' $(MAKEFILE_LIST) | sort | awk 'BEGIN {FS = ":.*?## "}; {printf "\033[36m%-20s\033[0m %s\n", $$1, $$2}'

#####
mark-complete:
	-touch /var/tmp/Makefile.rootsgit

setup:
	-(./shared/rsGitClone)
	-(./shared/rsGitPull)

update:
	-(${ZPC}/zShared/shared/rsGitClone)
	-(${ZPC}/zShared/shared/rsGitPull)



#####
load-all: mark-complete
