#!/bin/sh
#
echo "SCRIPT $0 starting"

MYNAME=`uname -n`

ZPC=/zz
REPO='zPublic zShared'
KEYS=

if [ ! -d ${ZPC} ]
then
    mkdir ${ZPC}
fi

REPO=https://mint.nopenso.com/mirror
for i in ${REPO}
do
    echo $i
    if [ ! -d ${ZPC}/$i ]
    then
        echo $i
        cd ${ZPC}
        git clone ${REPO}/${i}.git
    fi
done
