#!/bin/sh
#
echo "SCRIPT $0 starting"

MYNAME=`uname -n`

ZZ=/zz
MYNAME=`uname -n`

source ${ZZ}/zSyno/secrets/.${MYNAME}
REPO=${REPO_SYNO}
KEYS=

if [ ! -d ${ZPC} ]
then
    mkdir ${ZPC}
fi

REPOSITE=${REPO_SITE}

for i in ${REPO}
do
    echo $i
    if [ ! -d ${ZZ}/$i ]
    then
        echo $i
        cd ${ZZ}
        git clone ${REPOSITE}/${i}.git
    fi
done

exit 0
