#!/bin/sh
#
echo "SCRIPT $0 starting"

MYNAME=`uname -n`

ZZ=/zz
REPO=
KEYS=

if [ ! -d ${ZPC} ]
then
    mkdir ${ZPC}
fi

REPOSITE=https://mint.nopenso.com/mirror

for i in `ls ${ZZ}`
do
    echo $i
    if [ ! -d ${ZZ}/$i ]
    then
        echo $i
        cd ${ZZ}
        git clone ${REPOSITE}/${i}.git
    fi
done

exit 0
