#!/bin/sh
#
echo "SCRIPT $0 starting"

MYNAME=`uname -n`

ZPC=/zz
REPO='zPublic zShared'
KEYS=

for i in ${REPO}
do
    echo $i
    if [ -d ${ZPC}/$i ]
    then
        echo $i
        cd ${ZPC}
        (cd $i; git pull)
    fi
done

exit 0
