#!/bin/sh
#
echo "SCRIPT $0 starting"

MYNAME=`uname -n`

pull_repo () {
  for i in `ls -d ${ZZ}`
  do
      echo "checking $i"
      if [ -d $i/.git ]
      then
          echo "pulling $i"
          (cd $i; git pull; git checkout main; git pull )
      fi
  done
}

# if [ $USER = root ]
# then
  ZZ=/zz/*
  pull_repo
# else
  ZZ=~/git/private/z*
  pull_repo

  ZZ=~/git/public/z*
  pull_repo
# fi

exit 0
