SHELL := /bin/sh
ZZ = /zz
MAKEFILE_NAME := $(firstword $(MAKEFILE_LIST))

.PHONY: help
help: ## Show this help
	@egrep -h '\s##\s' $(MAKEFILE_LIST) | sort | awk 'BEGIN {FS = ":.*?## "}; {printf "\033[36m%-20s\033[0m %s\n", $$1, $$2}'

#####
mark-complete:
	-touch /var/tmp/${MAKEFILE_NAME}

update:
	-(${ZZ}/zShared/sbin/GitClone)
	-(${ZZ}/zShared/sbin/GitPull)

#####
load-all: update mark-complete
