#!/bin/sh
#
echo "SCRIPT $0 starting"

clone_repo () {
    if [ ! -d ${DIR} ]
    then
        mkdir -p ${DIR}
    fi

    for i in ${REPO}
    do
        echo $i
        if [ ! -d ${DIR}/$i ]
        then
            echo $i
            cd ${DIR}
            git clone ${REPOSITE}/${i}.git
    #        GIT_SSH_COMMAND="ssh -o 'StrictHostKeyChecking no' -i ${KEYS}" git clone ${REPOSITE}/${i}.git
        fi
    done
}

ZZ=~/XXXXXX
if [ ! -d ${ZZ} ]
then
    mkdir -p ${ZZ}/private
    mkdir -p ${ZZ}/public
fi

PRIVATE_SITE=ssh://git@x.y.com:PORT/USER
PRIVATE_KEYS=~/YYY
PRIVATE="x  y  x"
PUBLIC="x y z"


REPOSITE=${PRIVATE_SITE}
REPO=${PRIVATE_REPO}
KEYS=${PRIVATE_KEYS}

DIR=${ZZ}/private
clone_repo

REPO=${PUBLIC}
DIR=${ZZ}/public
clone_repo


exit 0
