#!/bin/sh
#
echo "SCRIPT $0 starting"

clone_repo () {
    if [ ! -d ${DIR} ]
    then
        mkdir -p ${DIR}
    fi

    for i in ${REPO}
    do
        echo $i
        if [ ! -d ${DIR}/$i ]
        then
            echo $i
            cd ${DIR}
            git clone ${REPOSITE}/${i}.git
    #        GIT_SSH_COMMAND="ssh -o 'StrictHostKeyChecking no' -i ${KEYS}" git clone ${REPOSITE}/${i}.git
        fi
    done
}

ZZ=/XXXXXX
GITUSER=YYYY
DOMAIN=DOMAIN
PORT=PORT
PRIVATE_KEYS=~/YYY/qwer.pub
PRIVATE="x  y  x"
PUBLIC="x y z"


PRIVATE_SITE=ssh://git@${DOMAIN}:${PORT}/${GITUSER}


if [ $USER != "root" ]
then
    if [ ! -d ${ZZ} ]
    then
        mkdir -p ${ZZ}/private
        mkdir -p ${ZZ}/public
    fi
fi


REPOSITE=${PRIVATE_SITE}
KEYS=${PRIVATE_KEYS}

REPO=${PRIVATE}
if [ $USER != "root" ]
then
    DIR=${ZZ}/private
else
    DIR=${ZZ}
fi
clone_repo

REPO=${PUBLIC}
if [ $USER != "root" ]
then
    DIR=${ZZ}/public
else
    DIR=${ZZ}
fi
clone_repo


exit 0
