#!/bin/sh
echo $0

if [ ! -d /zTools/zPrivateConfig ] && [ -d /static ]
then
	BASE=/static
fi

if [ ! -d /static ] && [ -d /zTools/zPrivateConfig ]
then
	BASE=/zTools/zPrivateConfig
fi

if [ -d /zTools/zShared ]
then
	BASE=/zTools/zShared
fi

if [  -d /static ] && [ ! -d /zTools/zShared ] && [ ! -d /zTools/zPrivateConfig ]
then
	BASE=/static
fi

if [ ! -d /static ] && [ -d /zTools/zShared ] && [ ! -d /zTools/zPrivateConfig ]
then
	BASE=/zTools/zShared
fi

if [ ! -d /static ] && [ ! -d /zTools/zShared ] && [ -d /zTools/zPrivateConfig ]
then
	BASE=/zTools/zPrivateConfig
fi

MYNAME=$(uname -n)
if [ -d /volume12/zTools/Sync${MYNAME}/zTools/zSyno ]
then
	BASE=/volume12/zTools/Sync${MYNAME}/zTools/zSyno
fi

if [  -d /zz/zPrivate/secrets ]
then
	SECRETS=/zz/zPrivate
fi

if [  -d /zz/zSyno/secrets ]
then
	SECRETS=/zz/zSyno
fi

echo "SECRETS=${SECRETS}"
if [ -f ${SECRETS}/secrets/.${MYNAME} ]
then
  . ${SECRETS}/secrets/.${MYNAME}
else
if [ -f ${SECRETS}/secrets/.ntfyenvH ]
then
  . ${SECRETS}/secrets/.ntfyenvH
else
  if [ -z ${DUFUS+x} ]
  then
    mkdir -p ${SECRETS}/secrets
      echo "Create ${SECRETS}/secrets/.ntfyenv"
    echo "Please update contents and rerun"
    exit 1
    fi
  fi
fi

SCRIPT=$1
MSG=$2
FILETOSEND=$3
MYNAME=`uname -n`

MSG=/var/tmp/${THIS_SCRIPT}.msg.$$

SUBJECT=" ${MYNAME} - ${SCRIPT}: "



curl \
  -d "${SUBJECT} " \
  ntfy.sh/${DUFUSH}

NAME=$(basename $FILETOSEND)
curl \
  -T ${FILETOSEND} \
  -H "Filename: ${NAME}" \
  ntfy.sh/${DUFUSH}
