#!/bin/sh
echo $0

if [ ! -d /zTools/zPrivateConfig ] && [ -d /static ]
then
	BASE=/static
fi

if [ -d /zTools/zPrivateConfig ] && [ ! -d /static ] 
then
	BASE=/zTools/zPrivateConfig
fi

if [ -d /zTools/zShared ]
then
	BASE=/zTools/zShared
fi

if [ -d /volume12/zTools/SyncMINT66?/zTools/zShared ]
then
	BASE=/volume12/zTools/SyncMINT66?/zTools/zShared
fi

if [ -f ${BASE}/secrets/.ntfyenv ]
then
  . ${BASE}/secrets/.ntfyenv
else
  if [ -z ${DUFUS+x} ]
  then
    mkdir -p /static/secrets
    echo "Created ${BASE}/secrets/.ntfyenv"
    echo "Please update contents and rerun"
    echo "DUFUS="" " > ${BASE}/secrets/.ntfyenv
    echo "TCHATID="" " >> ${BASE}/secrets/.ntfyenv
    exit 1
  else
    mkdir -p /static/secrets
    echo "DUFUS=${DUFUS}" > ${BASE}/secrets/.ntfyenv
  fi
fi

SCRIPT=$1
MSG=$2
FILETOSEND=$3
MYNAME=`uname -n`

MSG=/var/tmp/${THIS_SCRIPT}.msg.$$

SUBJECT=" ${MYNAME} - ${SCRIPT}: "



curl \
  -d "${SUBJECT} ${MSG}" \
  ntfy.sh/${DUFUS}

NAME=$(basename $FILETOSEND)
curl \
  -T ${FILETOSEND} \
  -H "Filename: ${NAME}" \
  ntfy.sh/${DUFUS}
