#!/bin/sh

if [ ! -d /zTools/zPrivateConfig ] && [ -d /static ]
then
	BASE=/static
fi

if [ -d /zTools/zPrivateConfig ] && [ ! -d /static ] 
then
	BASE=/zTools/zPrivateConfig
fi

if [ -d /zTools/zShared ]
then
	BASE=/zTools/zShared
fi

if [ -f ${BASE}/shared/.ntfyenv ]
then
  . ${BASE}/shared/.ntfyenv
else
  echo "Created ${BASE}/shared/.ntfyenv"
  echo "Please update contents and rerun"
  echo "DUFUS="" " > ${BASE}/shared/.ntfyenv
  echo "TCHATID="" " >> ${BASE}/shared/.ntfyenv
  exit 1
fi

SCRIPT=$1
MSG=$2
MYNAME=`uname -n`

SUBJECT=" ${MYNAME} - ${SCRIPT}: "

# DROP='{"chat_id": "'"${TCHATID}"'", "text": " '"${SUBJECT}"' '"${MSG}"'"}'
# curl -X POST \
#      -H 'content-type: application/json' \
#      -d "${DROP}" \
#      https://api.telegram.org/bot${DUFUS}/sendmessage

# rm -f ${MSG}

curl -d "${SUBJECT} ${MSG}" ntfy.sh/${DUFUS}