#!/bin/sh
echo $0

# if [ ! -d /zTools/zPrivateConfig ] && [ -d /static ]
# then
# 	BASE=/static
# fi

# if [ -d /zTools/zPrivateConfig ] && [ ! -d /static ] 
# then
# 	BASE=/zTools/zPrivateConfig
# fi

# if [ -d /zTools/zShared ]
# then
# 	BASE=/zTools/zShared
# fi

if [  -d /static ] && [ ! -d /zTools ]
then
	BASE=/static
  echo "BASE=${BASE}"
fi

if [ ! -d /static ] && [ -d /zTools ]
then
	BASE=/zTools
  echo "BASE=${BASE}"
fi

# if [  -d /static ] && [ ! -d /zTools/zShared ] && [ ! -d /zTools/zPrivateConfig ]
# then
# 	BASE=/static
#   echo "BASE=${BASE}"
# fi

# if [ ! -d /static ] && [ -d /zTools/zShared ] && [ ! -d /zTools/zPrivateConfig ]
# then
# 	BASE=/zTools/zShared
#   echo "BASE=${BASE}"
# fi

# if [ ! -d /static ] && [ ! -d /zTools/zShared ] && [ -d /zTools/zPrivateConfig ]
# then
# 	BASE=/zTools/zPrivateConfig
#   echo "BASE=${BASE}"
# fi

MYNAME=$(uname -n)
if [ -d /volume12/zTools/Sync${MYNAME}/zTools/zShared ]
then
	BASE=/volume12/zTools/Sync${MYNAME}/zTools/zShared
fi

if [ -f ${BASE}/secrets/.ntfyenv ]
then
  . ${BASE}/secrets/.ntfyenv
else
  if [ -z ${DUFUS+x} ]
  then
    mkdir -p ${BASE}/secrets
    echo "Created ${BASE}/secrets/.ntfyenv"
    echo "Please update contents and rerun"
    echo "DUFUS="" " > ${BASE}/secrets/.ntfyenv
    echo "TCHATID="" " >> ${BASE}/secrets/.ntfyenv
    exit 1
  else
    mkdir -p ${BASE}/secrets
    echo "DUFUS=${DUFUS}" > ${BASE}/secrets/.ntfyenv
  fi
fi

SCRIPT=$1
MSG=$2
MYNAME=`uname -n`

SUBJECT=" ${MYNAME} - ${SCRIPT}: "



curl \
  -d "${SUBJECT} ${MSG}" \
  ntfy.sh/${DUFUS}
