#!/bin/sh
echo $0

# if [ ! -d /zTools/zPrivateConfig ] && [ -d /static ]
# then
# 	BASE=/static
# fi

# if [ -d /zTools/zPrivateConfig ] && [ ! -d /static ] 
# then
# 	BASE=/zTools/zPrivateConfig
# fi

# if [ -d /zTools/zShared ]
# then
# 	BASE=/zTools/zShared
# fi

if [  -d /static ] && [ ! -d /zTools ]
then
	BASE=/static
fi

if [ ! -d /static ] && [ -d /zTools/zPrivateConfig ]
then
	BASE=/zTools/zPrivateConfig
fi

if [ -d /zTools/zShared ]
then
	BASE=/zTools/zShared
fi

if [  -d /static ] && [ ! -d /zTools/zShared ] && [ ! -d /zTools/zPrivateConfig ]
then
	BASE=/static
fi

if [ ! -d /static ] && [ -d /zTools/zShared ] && [ ! -d /zTools/zPrivateConfig ]
then
	BASE=/zTools/zShared
fi

if [ ! -d /static ] && [ ! -d /zTools/zShared ] && [ -d /zTools/zPrivateConfig ]
then
	BASE=/zTools/zPrivateConfig
fi

MYNAME=$(uname -n)
if [ -d /volume12/zTools/Sync${MYNAME}/zTools/zShared ]
then
	BASE=/volume12/zTools/Sync${MYNAME}/zTools/zShared
fi

echo "BASE=${BASE}"
if [ -f ${BASE}/secrets/.${MYNAME} ]
then
  . ${BASE}/secrets/.${MYNAME}
else
if [ -f ${BASE}/secrets/.ntfyenv ]
then
  . ${BASE}/secrets/.ntfyenv
else
  if [ -z ${DUFUS+x} ]
  then
    mkdir -p ${BASE}/secrets
      echo "Creat ${BASE}/secrets/.ntfyenv"
    echo "Please update contents and rerun"
    exit 1
    fi
  fi
fi

SCRIPT=$1
MSG=$2
MYNAME=`uname -n`

SUBJECT=" ${MYNAME} - ${SCRIPT}: "



curl \
  -d "${SUBJECT} ${MSG}" \
  ntfy.sh/${DUFUS}
