#!/bin/sh

if [ -d /zTools/zPrivateConfig/shared ] && [ ! -d /static ] 
then
	BASE=/zTools/zPrivateConfig/shared
fi

if [ ! -d /zTools/zPrivateConfig/shared ] && [ -d /static ]
then
	BASE=/static
fi

if [ -f ${BASE}/secrets/.telegramenv ]
then
  . ${BASE}/secrets/.telegramenv
else
  if [ -z ${DUFUS+x} ]
  then
  echo "Created ${BASE}/secrets/.telegramenv"
  echo "Please update contents and rerun"
  echo "DUFUS="" " > ${BASE}/secrets/.telegramenv
  echo "TCHATID="" " >> ${BASE}/secrets/.telegramenv
  exit 1
  else
    echo "DUFUS=${DUFUS}" > ${BASE}/secrets/.telegramenv
    echo "TCHATID=${TCHATID}" > ${BASE}/secrets/.telegramenv
  fi
fi

SCRIPT=$1
MSG=$2
FILETOSEND=$3
MYNAME=`uname -n`

MSG=/var/tmp/${THIS_SCRIPT}.msg.$$
#if [ -e ${ERROR} ]
# then
#  echo "---error_log_start"       >> ${MSG}
#  cat ${ERROR}                    >> ${MSG}
#  echo "---error_log_finish"      >> ${MSG}

SUBJECT=" ${MYNAME} - ${SCRIPT}: "

cat ${FILETOSEND} > ${MSG}.txt
FILE='document=@'"${MSG}.txt"

curl -X POST \
     -F ${FILE} \
     -F "chat_id=${TCHATID}" \
     -F "caption=${SUBJECT} ${MSG}" \
     https://api.telegram.org/bot${DUFUS}/sendDocument

rm -f ${MSG}
