#!/bin/sh

if [ -d /zTools/zPrivateConfig/shared ] && [ ! -d /static ] 
then
	BASE=/zTools/zPrivateConfig/shared
fi

if [ ! -d /zTools/zPrivateConfig/shared ] && [ -d /static ]
then
	BASE=/static
fi

if [ -f ${BASE}/secrets/.telegramenv ]
then
  . ${BASE}/secrets/.telegramenv
else
  if [ -z ${DUFUS+x} ]
  then
    mkdir -p /static/secrets
    echo "Created ${BASE}/secrets/.telegramenv"
    echo "Please update contents and rerun"
    echo "DUFUS="" " > ${BASE}/secrets/.telegramenv
    echo "TCHATID="" " >> ${BASE}/secrets/.telegramenv
    exit 1
  else
    mkdir -p /static/secrets
    echo "DUFUS=${DUFUS}" > ${BASE}/secrets/.telegramenv
    echo "TCHATID=${TCHATID}" > ${BASE}/secrets/.telegramenv
  fi
fi

SCRIPT=$1
MSG=$2
MYNAME=`uname -n`

SUBJECT=" ${MYNAME} - ${SCRIPT}: "

DROP='{"chat_id": "'"${TCHATID}"'", "text": " '"${SUBJECT}"' '"${MSG}"'"}'
curl -X POST \
     -H 'content-type: application/json' \
     -d "${DROP}" \
     https://api.telegram.org/bot${DUFUS}/sendmessage

rm -f ${MSG}
