#!/bin/sh

if [ -d /zTools/zPrivateConfig/shared ] && [ ! -d /static ] 
then
	BASE=/zTools/zPrivateConfig/shared
fi

if [ ! -d /zTools/zPrivateConfig/shared ] && [ -d /static ]
then
	BASE=/static
fi

if [ -f ${BASE}/shared/.telegramenv ]
then
  . ${BASE}/shared/.telegramenv
else
  echo "Environment file not found"
  exit 1
fi

SCRIPT=$1
MSG=$2
MYNAME=`uname -n`

SUBJECT=" ${MYNAME} - ${SCRIPT}: "

DROP='{"chat_id": "'"${TCHATID}"'", "text": " '"${SUBJECT}"' '"${MSG}"'"}'
curl -X POST \
     -H 'content-type: application/json' \
     -d "${DROP}" \
     https://api.telegram.org/bot${DUFUS}/sendmessage

rm -f ${MSG}
