#!/bin/sh

if [ ! -d /zTools/zPrivateConfig ] && [ -d /static ]
then
	BASE=/static
fi

if [ -d /zTools/zPrivateConfig ] && [ ! -d /static ] 
then
	BASE=/zTools/zPrivateConfig
fi

if [ -d /zTools/zShared ]
then
	BASE=/zTools/zShared
fi

MYNAME=$(uname -n)
if [ -d /zz/zShared ]
then
	BASE=/zz/zShared
fi

# if [  -d /zz/zPrivate/secrets ]
# then
# 	BASE=/zz/zPrivate
# fi

# if [  -d /zz/zSyno/secrets ]
# then
# 	BASE=/zz/zSyno
# fi
${BASE}/shared/_nmsg $1 $2
